services:
  - type: web
    name: catway-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: URL_MONGO
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: SECURE_COOKIE
        sync: false
      - key: URL_FRONT
        sync: false